from unittest.mock import MagicMock
from api.exceptions.validation_exception import ValidationException
import unittest


class TestStore(unittest.TestCase):
    pass